// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cX1M1-05B85YdqQFjSdXlcCy7J0mQBs',
    appId: '1:164149930104:web:3e0ca0a8f1aded46d0e58d',
    messagingSenderId: '164149930104',
    projectId: 'flutter-todo-list-48655',
    authDomain: 'flutter-todo-list-48655.firebaseapp.com',
    storageBucket: 'flutter-todo-list-48655.appspot.com',
    measurementId: 'G-6THHGCC81S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEU_Nrs4Dt9lIeymmffTl4Qty7P9g5Em0',
    appId: '1:164149930104:android:e6664f632fc5e8d6d0e58d',
    messagingSenderId: '164149930104',
    projectId: 'flutter-todo-list-48655',
    storageBucket: 'flutter-todo-list-48655.appspot.com',
  );
}
